### ISSUE TITLE
关于函数执行的问题

### ISSUE THREAD

**Issue by KngZhi** [Phoebe-Perry/ife_baidu_2016#2]
您是如何做到按钮被点击时，数据不再重复出现？看了下代码，并没有发现啊，求解惑。

**Comment by Phoebe-Perry** [comment]
请问你说的是哪段代码呢，时间太长了不知道是哪个部分

**Comment by KngZhi** [comment]
我之后再仔细看了下你的代码就找到了疑惑的部分，第一次有点迷~ 谢谢回复啦 ：)
